version: '3'
services:
  estoque:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: estoque/api
    ports:
      - '8080:8080'
    environment:
      - ADDITIONAL_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -Xmx1G -Xms128m -XX:MaxMetaspaceSize=128m
      - PROFILE=dev
    links:
      - db
      
  db:
    image: mysql:5.6
    ports:
      - "3306:3306"
    volumes:
      - ./docker/volume_mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=M@k120987
      - MYSQL_DATABASE=estoque
    
  app:
    image: phpmyadmin/phpmyadmin:latest
    links:
      - db
     
    ports:
      - 80:80
    environment:
      - PMA_ARBITRARY=1